// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as FormSubmit from "../../utils/FormSubmit.bs.js";

import './form-component-styles.css';
;

var initalInputs = {
  input1: "",
  input2: ""
};

function Form(Props) {
  var onSubmitHandler = Props.onSubmitHandler;
  var numberOfTransactions = Props.numberOfTransactions;
  var transactionNumberHandler = Props.transactionNumberHandler;
  var match = React.useState(function () {
        return initalInputs;
      });
  var setFormInputs = match[1];
  var formInputs = match[0];
  return React.createElement("div", {
              className: "form-component"
            }, React.createElement("h3", undefined, "Transaction Entry"), React.createElement("hr", undefined), React.createElement("div", {
                  className: "form-inputs"
                }), React.createElement("label", undefined, "Description"), React.createElement("br", undefined), React.createElement("input", {
                  className: "form-input1",
                  type: "text",
                  value: formInputs.input1,
                  onChange: (function ($$event) {
                      return FormSubmit.inputEventHandler($$event, /* Input1 */0, setFormInputs);
                    })
                }), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement("label", undefined, "Amount"), React.createElement("br", undefined), React.createElement("input", {
                  className: "form-input2",
                  type: "number",
                  value: formInputs.input2,
                  onChange: (function ($$event) {
                      return FormSubmit.inputEventHandler($$event, /* Input2 */1, setFormInputs);
                    })
                }), React.createElement("br", undefined), React.createElement("button", {
                  className: "button-submit",
                  onClick: (function (param) {
                      FormSubmit.onSubmitClick(formInputs, numberOfTransactions, onSubmitHandler, transactionNumberHandler);
                      return Curry._1(setFormInputs, (function (param) {
                                    return {
                                            input1: "",
                                            input2: ""
                                          };
                                  }));
                    })
                }, "Submit"));
}

var make = Form;

export {
  initalInputs ,
  make ,
  
}
/*  Not a pure module */
