// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";

function add(a, b) {
  return a + b | 0;
}

function Counter(Props) {
  var match = React.useState(function () {
        return 0;
      });
  var setCount = match[1];
  return React.createElement(React.Fragment, undefined, React.createElement("div", undefined, React.createElement("h3", undefined, String(match[0])), React.createElement("button", {
                      onClick: (function (param) {
                          return Curry._1(setCount, (function (prev) {
                                        return prev + 1 | 0;
                                      }));
                        })
                    }, "Add")));
}

var make = Counter;

export {
  add ,
  make ,
  
}
/* react Not a pure module */
