// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as EditData from "../../types/EditData.bs.js";
import * as Caml_array from "rescript/lib/es6/caml_array.js";
import * as FormStatic from "../../static/FormStatic.bs.js";

import './edit-component-styles.css';
;

var inputs = {
  index: -1
};

var formValues = {
  input1: "",
  input2: ""
};

function setIndex(inputIndex) {
  inputs.index = inputIndex;
  
}

function Edit(Props) {
  var editToggle = Props.editToggle;
  var transactions = Props.transactions;
  var setTransactions = Props.setTransactions;
  var match = React.useState(function () {
        return Caml_array.get(transactions, inputs.index).description;
      });
  var setInput1 = match[1];
  var input1 = match[0];
  var match$1 = React.useState(function () {
        return String(Caml_array.get(transactions, inputs.index).amount);
      });
  var setInput2 = match$1[1];
  var input2 = match$1[0];
  return React.createElement("div", {
              className: "edit-component"
            }, React.createElement("div", {
                  className: "background-popup-window"
                }, React.createElement("h3", undefined, "Edit Transaction"), React.createElement("form", {
                      onSubmit: (function (param) {
                          return EditData.onSubmitEdit(inputs, transactions, input1, input2, setTransactions);
                        })
                    }, React.createElement("div", {
                          className: "form-inputs"
                        }), React.createElement("label", undefined, FormStatic.input1Label), React.createElement("br", undefined), React.createElement("input", {
                          className: "form-input1",
                          title: FormStatic.input1TooltipText,
                          pattern: FormStatic.input1RegEx,
                          placeholder: FormStatic.input1Placeholder,
                          required: true,
                          type: "text",
                          value: input1,
                          onChange: (function ($$event) {
                              return Curry._1(setInput1, (function (param) {
                                            return $$event.target.value;
                                          }));
                            })
                        }), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement("label", undefined, FormStatic.input2Label), React.createElement("br", undefined), React.createElement("input", {
                          className: "form-input2",
                          title: FormStatic.input2TooltipText,
                          pattern: FormStatic.input2RegEx,
                          placeholder: FormStatic.input2Placeholder,
                          required: true,
                          type: "text",
                          value: input2,
                          onChange: (function ($$event) {
                              return Curry._1(setInput2, (function (param) {
                                            return $$event.target.value;
                                          }));
                            })
                        }), React.createElement("br", undefined), React.createElement("button", {
                          className: "button-submit",
                          type: "submit"
                        }, FormStatic.buttonText)), React.createElement("button", {
                      className: "button-submit",
                      onClick: (function (param) {
                          return Curry._1(editToggle, (function (prev) {
                                        return !prev;
                                      }));
                        })
                    }, "Exit")));
}

var make = Edit;

export {
  inputs ,
  formValues ,
  setIndex ,
  make ,
  
}
/*  Not a pure module */
