// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

var defaultTxnObj_transactions = [];

function defaultTxnObj_transaction_setter(param) {
  
}

function defaultTxnObj_transaction_number_setter(param) {
  
}

var defaultTxnObj = {
  transactions: defaultTxnObj_transactions,
  transaction_setter: defaultTxnObj_transaction_setter,
  transaction_number: -1,
  transaction_number_setter: defaultTxnObj_transaction_number_setter
};

var context = React.createContext(defaultTxnObj);

var provider = context.Provider;

function ContextTxn$TxnContext$Provider(Props) {
  var value = Props.value;
  var children = Props.children;
  return React.createElement(provider, {
              value: value,
              children: children
            });
}

var Provider = {
  provider: provider,
  make: ContextTxn$TxnContext$Provider
};

var TxnContext = {
  defaultTxnObj: defaultTxnObj,
  context: context,
  Provider: Provider
};

export {
  TxnContext ,
  
}
/* context Not a pure module */
