// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Caml_array from "rescript/lib/es6/caml_array.js";
import * as TypeConversions from "../utils/TypeConversions.bs.js";

function onSubmitEdit(inputs, transactions, input1, input2, setTransactions) {
  var transactionsCopy = transactions.slice();
  var amountNew = TypeConversions.string_to_float(input2);
  var editedTransaction_id = Caml_array.get(transactionsCopy, inputs.index).id;
  var editedTransaction_isPositive = amountNew > 0;
  var editedTransaction = {
    id: editedTransaction_id,
    description: input1,
    amount: amountNew,
    isPositive: editedTransaction_isPositive
  };
  Caml_array.set(transactionsCopy, inputs.index, editedTransaction);
  return Curry._1(setTransactions, (function (param) {
                return transactionsCopy;
              }));
}

export {
  onSubmitEdit ,
  
}
/* No side effect */
