// Generated by ReScript, PLEASE EDIT WITH CARE


function getAllBalances(allTransactions) {
  var allBalances = {
    balance: 0,
    income: 0,
    expense: 0
  };
  allTransactions.forEach(function (transaction) {
        if (transaction.amount > 0) {
          allBalances.income = allBalances.income + transaction.amount;
        } else {
          allBalances.expense = allBalances.expense - transaction.amount;
        }
        allBalances.balance = allBalances.balance + transaction.amount;
        
      });
  return allBalances;
}

export {
  getAllBalances ,
  
}
/* No side effect */
