// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Js_int from "rescript/lib/es6/js_int.js";

function deleteTransaction(transactionHandler, transactionNumber, transactions) {
  var transactionCopy = transactions.slice();
  transactionCopy.forEach(function (x, index) {
        if (Js_int.equal(x.id, transactionNumber)) {
          transactionCopy.splice(index, 1);
          return ;
        }
        
      });
  return Curry._1(transactionHandler, (function (param) {
                return transactionCopy;
              }));
}

export {
  deleteTransaction ,
  
}
/* No side effect */
