// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Js_int from "rescript/lib/es6/js_int.js";

function deleteTransaction(transactionHandler, transactionNumber, transactions) {
  var transactionCopy = transactions.slice();
  transactionCopy.forEach(function (x, index) {
        if (!Js_int.equal(x.id, transactionNumber)) {
          return ;
        }
        var wtf = transactionCopy.splice(index, 1);
        Curry._1(transactionHandler, (function (param) {
                return transactionCopy;
              }));
        console.log(transactionCopy, wtf);
        
      });
  
}

export {
  deleteTransaction ,
  
}
/* No side effect */
