// Generated by ReScript, PLEASE EDIT WITH CARE


function getDataFromLocal(dataField) {
  var localDataOption = localStorage.getItem(dataField);
  if (localDataOption !== null) {
    return localDataOption;
  } else {
    return "";
  }
}

function setDataToLocal(dataField, data) {
  var dataExtracted = data !== undefined ? data : "";
  localStorage.setItem(dataField, dataExtracted);
  
}

function localDataWrapper(param) {
  var localDataTransactions = getDataFromLocal("transactions-local");
  var initialStateTransactions = localDataTransactions !== "" ? JSON.parse(localDataTransactions) : [];
  var localTxnNumber = getDataFromLocal("transactions-number-local");
  var initalTxnNumber = localTxnNumber !== "" ? JSON.parse(localTxnNumber) : 0;
  return [
          initialStateTransactions,
          initalTxnNumber
        ];
}

export {
  getDataFromLocal ,
  setDataToLocal ,
  localDataWrapper ,
  
}
/* No side effect */
