// Generated by ReScript, PLEASE EDIT WITH CARE


function getDataFromLocal(dataField) {
  var localDataOption = localStorage.getItem(dataField);
  if (localDataOption !== null) {
    return localDataOption;
  } else {
    return "";
  }
}

function setDataToLocal(dataField, data) {
  var dataExtracted = data !== undefined ? data : "";
  localStorage.setItem(dataField, dataExtracted);
  
}

export {
  getDataFromLocal ,
  setDataToLocal ,
  
}
/* No side effect */
