// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Float from "rescript/lib/es6/belt_Float.js";

function float_to_RString(input) {
  return String(input);
}

function string_to_float(input) {
  var holder1 = Belt_Float.fromString(input);
  if (holder1 !== undefined) {
    return holder1;
  } else {
    return 0.0;
  }
}

export {
  float_to_RString ,
  string_to_float ,
  
}
/* No side effect */
