// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

function $$History(Props) {
  var allTransactions = Props.allTransactions;
  return React.createElement("div", {
              className: "history-component"
            }, React.createElement("h3", undefined, "History Component"), Belt_Array.map(allTransactions, (function (transaction) {
                    return React.createElement("li", undefined, transaction.description + " " + transaction.amount.toString() + " " + String(transaction.isPositive));
                  })), React.createElement("hr", undefined));
}

var make = $$History;

export {
  make ,
  
}
/* react Not a pure module */
