// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as ContextTxn from "../Context/ContextTxn.bs.js";
import * as HistoryUtils from "../../utils/HistoryUtils.bs.js";
import * as HistoryStatic from "../../static/HistoryStatic.bs.js";
import * as TypeConversions from "../../utils/TypeConversions.bs.js";

import './history-component-styles.css';
;

function $$History(Props) {
  var editTxnToggle = Props.editTxnToggle;
  var match = React.useContext(ContextTxn.TxnContext.context);
  var transaction_setter = match.transaction_setter;
  var transactions = match.transactions;
  return React.createElement("div", {
              className: "history-component"
            }, React.createElement("h3", {
                  className: "history-title"
                }, HistoryStatic.header), React.createElement("hr", undefined), React.createElement("div", {
                  className: "history-parent"
                }, Belt_Array.map(transactions, (function (transaction) {
                        var bgColor = transaction.isPositive ? "history-item-positive" : "history-item-negative";
                        return React.createElement("div", {
                                    key: String(transaction.id),
                                    className: "history-item"
                                  }, React.createElement("div", {
                                        className: "history-item-text"
                                      }, React.createElement("p", {
                                            className: "history-item-description"
                                          }, transaction.description), React.createElement("p", {
                                            className: "history-item-amount"
                                          }, TypeConversions.float_to_RString(transaction.amount)), React.createElement("div", {
                                            className: "history-item-end-strip " + bgColor
                                          }, React.createElement("button", {
                                                className: "history-item-button",
                                                id: String(transaction.id),
                                                onClick: (function ($$event) {
                                                    return HistoryUtils.deleteTransaction(transaction_setter, transaction.id, transactions);
                                                  })
                                              }, React.createElement("i", {
                                                    className: "fa-solid fa-trash"
                                                  })), React.createElement("button", {
                                                className: "history-item-edit-button",
                                                id: String(transaction.id),
                                                onClick: (function ($$event) {
                                                    return HistoryUtils.editTransaction(editTxnToggle, transaction.id, transactions);
                                                  })
                                              }, React.createElement("i", {
                                                    className: "fa fa-edit"
                                                  })))));
                      }))));
}

var make = $$History;

export {
  make ,
  
}
/*  Not a pure module */
