// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as TypeConversions from "../../utils/TypeConversions.bs.js";

import './History.component.css';
;

function $$History(Props) {
  var allTransactions = Props.allTransactions;
  return React.createElement("div", {
              className: "history-component"
            }, React.createElement("h3", {
                  className: "history-title"
                }, "Transaction History"), React.createElement("hr", undefined), React.createElement("div", {
                  className: "history-parent"
                }, Belt_Array.map(allTransactions, (function (transaction) {
                        var bgColor = transaction.isPositive ? "history-item-positive" : "history-item-negative";
                        return React.createElement("div", {
                                    key: String(transaction.id),
                                    className: "history-item"
                                  }, React.createElement("div", {
                                        className: "history-item-text"
                                      }, React.createElement("p", {
                                            className: "history-item-description"
                                          }, transaction.description), React.createElement("p", {
                                            className: "history-item-amount"
                                          }, TypeConversions.float_to_RString(transaction.amount)), React.createElement("div", {
                                            className: "history-item-end-strip " + bgColor
                                          }, React.createElement("button", {
                                                className: "history-item-button",
                                                id: String(transaction.id)
                                              }))));
                      }))), React.createElement("hr", undefined));
}

var make = $$History;

export {
  make ,
  
}
/*  Not a pure module */
