// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

function Balance(Props) {
  var allTransactions = Props.allTransactions;
  var allAmount = allTransactions.map(function (x) {
        return x.amount;
      });
  var allIncome = allTransactions.map(function (x) {
        if (x.amount > 0) {
          return x.amount;
        } else {
          return 0;
        }
      });
  var allExpenses = allTransactions.map(function (x) {
        if (x.amount < 0) {
          return x.amount;
        } else {
          return 0;
        }
      });
  var totalBalance = Belt_Array.reduce(allAmount, 0, (function (acc, value) {
          return acc + value | 0;
        }));
  var totalIncome = Belt_Array.reduce(allIncome, 0, (function (acc, value) {
          return acc + value | 0;
        }));
  var totalExpense = Belt_Array.reduce(allExpenses, 0, (function (acc, value) {
          return acc - value | 0;
        }));
  return React.createElement("div", undefined, React.createElement("h3", undefined, "Balance Component"), React.createElement("ul", undefined, React.createElement("li", undefined, "Balance: " + totalBalance.toString()), React.createElement("li", undefined, "Income: " + totalIncome.toString()), React.createElement("li", undefined, "Expense: " + totalExpense.toString())), React.createElement("hr", undefined));
}

var make = Balance;

export {
  make ,
  
}
/* react Not a pure module */
