// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as TypeConversions from "../../utils/TypeConversions.bs.js";
import * as BalanceInformation from "../../utils/BalanceInformation.bs.js";

import './balance-component-styles.css';
;

function Balance(Props) {
  var allTransactions = Props.allTransactions;
  var allBalances = BalanceInformation.getAllBalances(allTransactions);
  return React.createElement("div", {
              className: "balance-component"
            }, React.createElement("div", {
                  className: "balance-total"
                }, React.createElement("div", {
                      className: "balance-total-content"
                    }, React.createElement("p", undefined, "YOUR BALANCE"), React.createElement("h1", {
                          id: "balance-amount-display"
                        }, TypeConversions.float_to_RString(allBalances.balance)))), React.createElement("div", {
                  className: "balance-combined"
                }, React.createElement("div", {
                      className: "balance-combined-inner-white"
                    }, React.createElement("div", {
                          className: "balance-combined-income"
                        }, React.createElement("p", undefined, "INCOME"), React.createElement("p", {
                              className: "income-amount"
                            }, TypeConversions.float_to_RString(allBalances.income))), React.createElement("div", {
                          className: "balance-combined-expenses"
                        }, React.createElement("p", undefined, "EXPENSES"), React.createElement("p", {
                              className: "expense-amount"
                            }, TypeConversions.float_to_RString(allBalances.expense))))));
}

var make = Balance;

export {
  make ,
  
}
/*  Not a pure module */
