// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Edit from "./components/Edit/Edit.bs.js";
import * as Form from "./components/Form/Form.bs.js";
import * as React from "react";
import * as Balance from "./components/Balance/Balance.bs.js";
import * as $$History from "./components/History/History.bs.js";
import * as AppStatic from "./static/AppStatic.bs.js";
import * as FormUtils from "./utils/FormUtils.bs.js";
import * as LocalStorage from "./utils/LocalStorage.bs.js";

import './App.css';
;

function App(Props) {
  var match = LocalStorage.localDataWrapper(undefined);
  var initalTxnNumber = match[1];
  var initialStateTransactions = match[0];
  var match$1 = React.useState(function () {
        return initialStateTransactions;
      });
  var setTransactions = match$1[1];
  var transactions = match$1[0];
  var match$2 = React.useState(function () {
        return initalTxnNumber;
      });
  var numberOfTransactions = match$2[0];
  var match$3 = React.useState(function () {
        return false;
      });
  var setEditStatus = match$3[1];
  React.useEffect((function () {
          LocalStorage.setDataToLocal("transactions-local", JSON.stringify(transactions));
          LocalStorage.setDataToLocal("transactions-number-local", JSON.stringify(numberOfTransactions));
          
        }), [
        numberOfTransactions,
        transactions
      ]);
  return React.createElement("div", {
              className: "App"
            }, match$3[0] ? React.createElement(Edit.make, {
                    editToggle: setEditStatus,
                    transactions: transactions,
                    setTransactions: setTransactions
                  }) : React.createElement(React.Fragment, undefined), React.createElement("div", {
                  className: "top-bar"
                }, React.createElement("h1", undefined, AppStatic.overallHeader)), React.createElement("div", {
                  className: "all-content"
                }, React.createElement(Balance.make, {
                      allTransactions: transactions
                    }), React.createElement($$History.make, {
                      allTransactions: transactions,
                      transactionHandler: setTransactions,
                      editTxnToggle: setEditStatus
                    }), React.createElement(Form.make, {
                      onSubmitHandler: setTransactions,
                      numberOfTransactions: numberOfTransactions,
                      transactionNumberHandler: match$2[1],
                      onSubmitClick: FormUtils.onSubmitClick
                    })), React.createElement("div", {
                  className: "footer"
                }, React.createElement("p", undefined, AppStatic.footerText)));
}

var make = App;

export {
  make ,
  
}
/*  Not a pure module */
