// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Form from "./components/Form/Form.bs.js";
import * as React from "react";
import * as Balance from "./components/Balance/Balance.bs.js";
import * as $$History from "./components/History/History.bs.js";
import * as LocalStorage from "./utils/LocalStorage.bs.js";

import './App.css';
;

var localDataTransactions = LocalStorage.getDataFromLocal("transactions-local");

var initialStateTransactions = localDataTransactions !== "" ? JSON.parse(localDataTransactions) : [];

var localTxnNumber = LocalStorage.getDataFromLocal("transactions-number-local");

var initalTxnNumber = localTxnNumber !== "" ? JSON.parse(localTxnNumber) : 0;

function App(Props) {
  var match = React.useState(function () {
        return initialStateTransactions;
      });
  var setTransactions = match[1];
  var transactions = match[0];
  var match$1 = React.useState(function () {
        return initalTxnNumber;
      });
  var numberOfTransactions = match$1[0];
  React.useEffect((function () {
          LocalStorage.setDataToLocal("transactions-local", JSON.stringify(transactions));
          LocalStorage.setDataToLocal("transactions-number-local", JSON.stringify(numberOfTransactions));
          
        }), [
        numberOfTransactions,
        transactions
      ]);
  return React.createElement("div", {
              className: "App"
            }, React.createElement("div", {
                  className: "top-bar"
                }, React.createElement("h1", undefined, "Expense Tracker")), React.createElement("div", {
                  className: "all-content"
                }, React.createElement(Balance.make, {
                      allTransactions: transactions
                    }), React.createElement($$History.make, {
                      allTransactions: transactions,
                      transactionHandler: setTransactions
                    }), React.createElement(Form.make, {
                      onSubmitHandler: setTransactions,
                      numberOfTransactions: numberOfTransactions,
                      transactionNumberHandler: match$1[1]
                    })), React.createElement("div", {
                  className: "footer"
                }, React.createElement("p", undefined, "Made with <3 and ReScript")));
}

var make = App;

export {
  localDataTransactions ,
  initialStateTransactions ,
  localTxnNumber ,
  initalTxnNumber ,
  make ,
  
}
/*  Not a pure module */
